/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AsociereCopiiRouteImport } from './routes/asociere-copii'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificareShareIdRouteImport } from './routes/verificare.$shareId'
import { Route as SsoRoeidRouteImport } from './routes/sso.roeid'
import { Route as AuthenticatedSecretariatRouteImport } from './routes/_authenticated.secretariat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedSecretariatIndexRouteImport } from './routes/_authenticated.secretariat.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedSecretariatServiciiRouteImport } from './routes/_authenticated.secretariat.servicii'
import { Route as AuthenticatedSecretariatAsocieriRouteImport } from './routes/_authenticated.secretariat.asocieri'
import { Route as AuthenticatedDashboardSetariRouteImport } from './routes/_authenticated.dashboard.setari'
import { Route as AuthenticatedDashboardDocumenteRouteImport } from './routes/_authenticated.dashboard.documente'
import { Route as AuthenticatedDashboardCereriRouteImport } from './routes/_authenticated.dashboard.cereri'
import { Route as AuthenticatedDashboardBeneficiiRouteImport } from './routes/_authenticated.dashboard.beneficii'
import { Route as AuthenticatedDashboardAdmitereRouteImport } from './routes/_authenticated.dashboard.admitere'
import { Route as AuthenticatedDashboardAdaugaCopilRouteImport } from './routes/_authenticated.dashboard.adauga-copil'
import { Route as AuthenticatedSecretariatCerereIdRouteImport } from './routes/_authenticated.secretariat.cerere.$id'
import { Route as AuthenticatedDashboardCopilIdRouteImport } from './routes/_authenticated.dashboard.copil.$id'
import { Route as AuthenticatedDashboardCereriIdRouteImport } from './routes/_authenticated.dashboard.cereri.$id'

const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AsociereCopiiRoute = AsociereCopiiRouteImport.update({
  id: '/asociere-copii',
  path: '/asociere-copii',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificareShareIdRoute = VerificareShareIdRouteImport.update({
  id: '/verificare/$shareId',
  path: '/verificare/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoRoeidRoute = SsoRoeidRouteImport.update({
  id: '/sso/roeid',
  path: '/sso/roeid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSecretariatRoute =
  AuthenticatedSecretariatRouteImport.update({
    id: '/secretariat',
    path: '/secretariat',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretariatIndexRoute =
  AuthenticatedSecretariatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSecretariatRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedSecretariatServiciiRoute =
  AuthenticatedSecretariatServiciiRouteImport.update({
    id: '/servicii',
    path: '/servicii',
    getParentRoute: () => AuthenticatedSecretariatRoute,
  } as any)
const AuthenticatedSecretariatAsocieriRoute =
  AuthenticatedSecretariatAsocieriRouteImport.update({
    id: '/asocieri',
    path: '/asocieri',
    getParentRoute: () => AuthenticatedSecretariatRoute,
  } as any)
const AuthenticatedDashboardSetariRoute =
  AuthenticatedDashboardSetariRouteImport.update({
    id: '/setari',
    path: '/setari',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumenteRoute =
  AuthenticatedDashboardDocumenteRouteImport.update({
    id: '/documente',
    path: '/documente',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCereriRoute =
  AuthenticatedDashboardCereriRouteImport.update({
    id: '/cereri',
    path: '/cereri',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBeneficiiRoute =
  AuthenticatedDashboardBeneficiiRouteImport.update({
    id: '/beneficii',
    path: '/beneficii',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdmitereRoute =
  AuthenticatedDashboardAdmitereRouteImport.update({
    id: '/admitere',
    path: '/admitere',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdaugaCopilRoute =
  AuthenticatedDashboardAdaugaCopilRouteImport.update({
    id: '/adauga-copil',
    path: '/adauga-copil',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedSecretariatCerereIdRoute =
  AuthenticatedSecretariatCerereIdRouteImport.update({
    id: '/cerere/$id',
    path: '/cerere/$id',
    getParentRoute: () => AuthenticatedSecretariatRoute,
  } as any)
const AuthenticatedDashboardCopilIdRoute =
  AuthenticatedDashboardCopilIdRouteImport.update({
    id: '/copil/$id',
    path: '/copil/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCereriIdRoute =
  AuthenticatedDashboardCereriIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardCereriRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asociere-copii': typeof AsociereCopiiRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/secretariat': typeof AuthenticatedSecretariatRouteWithChildren
  '/sso/roeid': typeof SsoRoeidRoute
  '/verificare/$shareId': typeof VerificareShareIdRoute
  '/dashboard/adauga-copil': typeof AuthenticatedDashboardAdaugaCopilRoute
  '/dashboard/admitere': typeof AuthenticatedDashboardAdmitereRoute
  '/dashboard/beneficii': typeof AuthenticatedDashboardBeneficiiRoute
  '/dashboard/cereri': typeof AuthenticatedDashboardCereriRouteWithChildren
  '/dashboard/documente': typeof AuthenticatedDashboardDocumenteRoute
  '/dashboard/setari': typeof AuthenticatedDashboardSetariRoute
  '/secretariat/asocieri': typeof AuthenticatedSecretariatAsocieriRoute
  '/secretariat/servicii': typeof AuthenticatedSecretariatServiciiRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/secretariat/': typeof AuthenticatedSecretariatIndexRoute
  '/dashboard/cereri/$id': typeof AuthenticatedDashboardCereriIdRoute
  '/dashboard/copil/$id': typeof AuthenticatedDashboardCopilIdRoute
  '/secretariat/cerere/$id': typeof AuthenticatedSecretariatCerereIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asociere-copii': typeof AsociereCopiiRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/sso/roeid': typeof SsoRoeidRoute
  '/verificare/$shareId': typeof VerificareShareIdRoute
  '/dashboard/adauga-copil': typeof AuthenticatedDashboardAdaugaCopilRoute
  '/dashboard/admitere': typeof AuthenticatedDashboardAdmitereRoute
  '/dashboard/beneficii': typeof AuthenticatedDashboardBeneficiiRoute
  '/dashboard/cereri': typeof AuthenticatedDashboardCereriRouteWithChildren
  '/dashboard/documente': typeof AuthenticatedDashboardDocumenteRoute
  '/dashboard/setari': typeof AuthenticatedDashboardSetariRoute
  '/secretariat/asocieri': typeof AuthenticatedSecretariatAsocieriRoute
  '/secretariat/servicii': typeof AuthenticatedSecretariatServiciiRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/secretariat': typeof AuthenticatedSecretariatIndexRoute
  '/dashboard/cereri/$id': typeof AuthenticatedDashboardCereriIdRoute
  '/dashboard/copil/$id': typeof AuthenticatedDashboardCopilIdRoute
  '/secretariat/cerere/$id': typeof AuthenticatedSecretariatCerereIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/asociere-copii': typeof AsociereCopiiRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/secretariat': typeof AuthenticatedSecretariatRouteWithChildren
  '/sso/roeid': typeof SsoRoeidRoute
  '/verificare/$shareId': typeof VerificareShareIdRoute
  '/_authenticated/dashboard/adauga-copil': typeof AuthenticatedDashboardAdaugaCopilRoute
  '/_authenticated/dashboard/admitere': typeof AuthenticatedDashboardAdmitereRoute
  '/_authenticated/dashboard/beneficii': typeof AuthenticatedDashboardBeneficiiRoute
  '/_authenticated/dashboard/cereri': typeof AuthenticatedDashboardCereriRouteWithChildren
  '/_authenticated/dashboard/documente': typeof AuthenticatedDashboardDocumenteRoute
  '/_authenticated/dashboard/setari': typeof AuthenticatedDashboardSetariRoute
  '/_authenticated/secretariat/asocieri': typeof AuthenticatedSecretariatAsocieriRoute
  '/_authenticated/secretariat/servicii': typeof AuthenticatedSecretariatServiciiRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/secretariat/': typeof AuthenticatedSecretariatIndexRoute
  '/_authenticated/dashboard/cereri/$id': typeof AuthenticatedDashboardCereriIdRoute
  '/_authenticated/dashboard/copil/$id': typeof AuthenticatedDashboardCopilIdRoute
  '/_authenticated/secretariat/cerere/$id': typeof AuthenticatedSecretariatCerereIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asociere-copii'
    | '/contact'
    | '/despre'
    | '/dashboard'
    | '/secretariat'
    | '/sso/roeid'
    | '/verificare/$shareId'
    | '/dashboard/adauga-copil'
    | '/dashboard/admitere'
    | '/dashboard/beneficii'
    | '/dashboard/cereri'
    | '/dashboard/documente'
    | '/dashboard/setari'
    | '/secretariat/asocieri'
    | '/secretariat/servicii'
    | '/dashboard/'
    | '/secretariat/'
    | '/dashboard/cereri/$id'
    | '/dashboard/copil/$id'
    | '/secretariat/cerere/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asociere-copii'
    | '/contact'
    | '/despre'
    | '/sso/roeid'
    | '/verificare/$shareId'
    | '/dashboard/adauga-copil'
    | '/dashboard/admitere'
    | '/dashboard/beneficii'
    | '/dashboard/cereri'
    | '/dashboard/documente'
    | '/dashboard/setari'
    | '/secretariat/asocieri'
    | '/secretariat/servicii'
    | '/dashboard'
    | '/secretariat'
    | '/dashboard/cereri/$id'
    | '/dashboard/copil/$id'
    | '/secretariat/cerere/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/asociere-copii'
    | '/contact'
    | '/despre'
    | '/_authenticated/dashboard'
    | '/_authenticated/secretariat'
    | '/sso/roeid'
    | '/verificare/$shareId'
    | '/_authenticated/dashboard/adauga-copil'
    | '/_authenticated/dashboard/admitere'
    | '/_authenticated/dashboard/beneficii'
    | '/_authenticated/dashboard/cereri'
    | '/_authenticated/dashboard/documente'
    | '/_authenticated/dashboard/setari'
    | '/_authenticated/secretariat/asocieri'
    | '/_authenticated/secretariat/servicii'
    | '/_authenticated/dashboard/'
    | '/_authenticated/secretariat/'
    | '/_authenticated/dashboard/cereri/$id'
    | '/_authenticated/dashboard/copil/$id'
    | '/_authenticated/secretariat/cerere/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AsociereCopiiRoute: typeof AsociereCopiiRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  SsoRoeidRoute: typeof SsoRoeidRoute
  VerificareShareIdRoute: typeof VerificareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asociere-copii': {
      id: '/asociere-copii'
      path: '/asociere-copii'
      fullPath: '/asociere-copii'
      preLoaderRoute: typeof AsociereCopiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificare/$shareId': {
      id: '/verificare/$shareId'
      path: '/verificare/$shareId'
      fullPath: '/verificare/$shareId'
      preLoaderRoute: typeof VerificareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso/roeid': {
      id: '/sso/roeid'
      path: '/sso/roeid'
      fullPath: '/sso/roeid'
      preLoaderRoute: typeof SsoRoeidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/secretariat': {
      id: '/_authenticated/secretariat'
      path: '/secretariat'
      fullPath: '/secretariat'
      preLoaderRoute: typeof AuthenticatedSecretariatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secretariat/': {
      id: '/_authenticated/secretariat/'
      path: '/'
      fullPath: '/secretariat/'
      preLoaderRoute: typeof AuthenticatedSecretariatIndexRouteImport
      parentRoute: typeof AuthenticatedSecretariatRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/secretariat/servicii': {
      id: '/_authenticated/secretariat/servicii'
      path: '/servicii'
      fullPath: '/secretariat/servicii'
      preLoaderRoute: typeof AuthenticatedSecretariatServiciiRouteImport
      parentRoute: typeof AuthenticatedSecretariatRoute
    }
    '/_authenticated/secretariat/asocieri': {
      id: '/_authenticated/secretariat/asocieri'
      path: '/asocieri'
      fullPath: '/secretariat/asocieri'
      preLoaderRoute: typeof AuthenticatedSecretariatAsocieriRouteImport
      parentRoute: typeof AuthenticatedSecretariatRoute
    }
    '/_authenticated/dashboard/setari': {
      id: '/_authenticated/dashboard/setari'
      path: '/setari'
      fullPath: '/dashboard/setari'
      preLoaderRoute: typeof AuthenticatedDashboardSetariRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documente': {
      id: '/_authenticated/dashboard/documente'
      path: '/documente'
      fullPath: '/dashboard/documente'
      preLoaderRoute: typeof AuthenticatedDashboardDocumenteRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/cereri': {
      id: '/_authenticated/dashboard/cereri'
      path: '/cereri'
      fullPath: '/dashboard/cereri'
      preLoaderRoute: typeof AuthenticatedDashboardCereriRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/beneficii': {
      id: '/_authenticated/dashboard/beneficii'
      path: '/beneficii'
      fullPath: '/dashboard/beneficii'
      preLoaderRoute: typeof AuthenticatedDashboardBeneficiiRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admitere': {
      id: '/_authenticated/dashboard/admitere'
      path: '/admitere'
      fullPath: '/dashboard/admitere'
      preLoaderRoute: typeof AuthenticatedDashboardAdmitereRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/adauga-copil': {
      id: '/_authenticated/dashboard/adauga-copil'
      path: '/adauga-copil'
      fullPath: '/dashboard/adauga-copil'
      preLoaderRoute: typeof AuthenticatedDashboardAdaugaCopilRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/secretariat/cerere/$id': {
      id: '/_authenticated/secretariat/cerere/$id'
      path: '/cerere/$id'
      fullPath: '/secretariat/cerere/$id'
      preLoaderRoute: typeof AuthenticatedSecretariatCerereIdRouteImport
      parentRoute: typeof AuthenticatedSecretariatRoute
    }
    '/_authenticated/dashboard/copil/$id': {
      id: '/_authenticated/dashboard/copil/$id'
      path: '/copil/$id'
      fullPath: '/dashboard/copil/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCopilIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/cereri/$id': {
      id: '/_authenticated/dashboard/cereri/$id'
      path: '/$id'
      fullPath: '/dashboard/cereri/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCereriIdRouteImport
      parentRoute: typeof AuthenticatedDashboardCereriRoute
    }
  }
}

interface AuthenticatedDashboardCereriRouteChildren {
  AuthenticatedDashboardCereriIdRoute: typeof AuthenticatedDashboardCereriIdRoute
}

const AuthenticatedDashboardCereriRouteChildren: AuthenticatedDashboardCereriRouteChildren =
  {
    AuthenticatedDashboardCereriIdRoute: AuthenticatedDashboardCereriIdRoute,
  }

const AuthenticatedDashboardCereriRouteWithChildren =
  AuthenticatedDashboardCereriRoute._addFileChildren(
    AuthenticatedDashboardCereriRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdaugaCopilRoute: typeof AuthenticatedDashboardAdaugaCopilRoute
  AuthenticatedDashboardAdmitereRoute: typeof AuthenticatedDashboardAdmitereRoute
  AuthenticatedDashboardBeneficiiRoute: typeof AuthenticatedDashboardBeneficiiRoute
  AuthenticatedDashboardCereriRoute: typeof AuthenticatedDashboardCereriRouteWithChildren
  AuthenticatedDashboardDocumenteRoute: typeof AuthenticatedDashboardDocumenteRoute
  AuthenticatedDashboardSetariRoute: typeof AuthenticatedDashboardSetariRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCopilIdRoute: typeof AuthenticatedDashboardCopilIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdaugaCopilRoute:
      AuthenticatedDashboardAdaugaCopilRoute,
    AuthenticatedDashboardAdmitereRoute: AuthenticatedDashboardAdmitereRoute,
    AuthenticatedDashboardBeneficiiRoute: AuthenticatedDashboardBeneficiiRoute,
    AuthenticatedDashboardCereriRoute:
      AuthenticatedDashboardCereriRouteWithChildren,
    AuthenticatedDashboardDocumenteRoute: AuthenticatedDashboardDocumenteRoute,
    AuthenticatedDashboardSetariRoute: AuthenticatedDashboardSetariRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCopilIdRoute: AuthenticatedDashboardCopilIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedSecretariatRouteChildren {
  AuthenticatedSecretariatAsocieriRoute: typeof AuthenticatedSecretariatAsocieriRoute
  AuthenticatedSecretariatServiciiRoute: typeof AuthenticatedSecretariatServiciiRoute
  AuthenticatedSecretariatIndexRoute: typeof AuthenticatedSecretariatIndexRoute
  AuthenticatedSecretariatCerereIdRoute: typeof AuthenticatedSecretariatCerereIdRoute
}

const AuthenticatedSecretariatRouteChildren: AuthenticatedSecretariatRouteChildren =
  {
    AuthenticatedSecretariatAsocieriRoute:
      AuthenticatedSecretariatAsocieriRoute,
    AuthenticatedSecretariatServiciiRoute:
      AuthenticatedSecretariatServiciiRoute,
    AuthenticatedSecretariatIndexRoute: AuthenticatedSecretariatIndexRoute,
    AuthenticatedSecretariatCerereIdRoute:
      AuthenticatedSecretariatCerereIdRoute,
  }

const AuthenticatedSecretariatRouteWithChildren =
  AuthenticatedSecretariatRoute._addFileChildren(
    AuthenticatedSecretariatRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedSecretariatRoute: typeof AuthenticatedSecretariatRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedSecretariatRoute: AuthenticatedSecretariatRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AsociereCopiiRoute: AsociereCopiiRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  SsoRoeidRoute: SsoRoeidRoute,
  VerificareShareIdRoute: VerificareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
